#!/bin/bash
DC_DIR=docker-compose
EXEC="docker-compose -p ${USER} -f docker-compose.yml"
ARG=$1
shift
DEFAULT='up -d'
CMD=${@:-$DEFAULT}

if [ -z $ARG ]
then
    echo -e $USAGE;
elif [ $ARG = "dev" -o $ARG = "prod" ]
then
    ${EXEC} -f $DC_DIR/docker-compose.$ARG.yml down;
    ${EXEC} -f $DC_DIR/docker-compose.$ARG.yml $CMD;
else
    echo -e $USAGE;
fi
