version: "3.6"
services:
  api:
    command: start
    ports:
      - "${API_PORT}:${API_PORT}"
    expose:
      - "3000"
    stdin_open: false
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres:12.2-alpine
    expose:
      - "5432"
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./data/pg:/var/lib/postgresql/data
  nginx:
    image: nginx:1.17-alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    links:
      - api
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
